services:
  fagel-appen:
    container_name: fagelappen
    build: .
    ports:
     - 5000:5000
    environment:
     - ASPNETCORE_URLS=http://+:5000
     - ConnectionStrings__db=Host=db;Database=fagelappen;Username=postgres;Password=${POSTGRES_PASSWORD}
     - Startup__MigrateDatabase=true
     - Frontend__redirectUri=http://localhost:5000/
  db:
    container_name: db
    image: postgres:15.2
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432